//! Embedded NEXRAD station metadata for Tempest weather radar application.
//!
//! This module contains a static array of known NEXRAD radar station metadata,
//! including station ID, name, geographic coordinates, and elevation.
//!
//! Station data is sourced from NOAA's NEXRAD station list. Coordinates are
//! approximate center points for each radar location.

/// Static station metadata for known NEXRAD radars.
///
/// Each entry contains:
/// - `id`: 4-letter ICAO identifier
/// - `name`: Human-readable station name
/// - `lat`: Latitude in decimal degrees
/// - `lon`: Longitude in decimal degrees
/// - `elevation_m`: Station elevation in meters
pub(crate) const STATIONS: &[StationData] = &[
    // Continental US Stations
    StationData {
        id: "KABR",
        name: "Aberdeen, South Dakota",
        lat: 45.4558,
        lon: -98.4128,
        elevation_m: 395.0,
    },
    StationData {
        id: "KABX",
        name: "Albuquerque, New Mexico",
        lat: 35.1299,
        lon: -106.8222,
        elevation_m: 1770.0,
    },
    StationData {
        id: "KADW",
        name: "Andrews Air Force Base, Maryland",
        lat: 38.8108,
        lon: -76.8658,
        elevation_m: 85.0,
    },
    StationData {
        id: "KAKQ",
        name: "Wakefield, Virginia",
        lat: 36.9840,
        lon: -77.0070,
        elevation_m: 34.0,
    },
    StationData {
        id: "KAMX",
        name: "Miami, Florida",
        lat: 25.6108,
        lon: -80.6853,
        elevation_m: 6.0,
    },
    StationData {
        id: "KAPX",
        name: "Gaylord, Michigan",
        lat: 44.9046,
        lon: -84.7074,
        elevation_m: 445.0,
    },
    StationData {
        id: "KARX",
        name: "La Crosse, Wisconsin",
        lat: 43.8226,
        lon: -91.1914,
        elevation_m: 397.0,
    },
    StationData {
        id: "KATX",
        name: "Seattle, Washington",
        lat: 48.1947,
        lon: -122.4914,
        elevation_m: 175.0,
    },
    StationData {
        id: "KBBX",
        name: "Beale Air Force Base, California",
        lat: 39.4966,
        lon: -121.6328,
        elevation_m: 32.0,
    },
    StationData {
        id: "KBGM",
        name: "Binghamton, New York",
        lat: 42.2378,
        lon: -75.9847,
        elevation_m: 490.0,
    },
    StationData {
        id: "KBHX",
        name: "Eureka, California",
        lat: 40.4988,
        lon: -124.2919,
        elevation_m: 236.0,
    },
    StationData {
        id: "KBUF",
        name: "Buffalo, New York",
        lat: 42.9487,
        lon: -78.7369,
        elevation_m: 207.0,
    },
    StationData {
        id: "KBYX",
        name: "Key West, Florida",
        lat: 24.5961,
        lon: -81.7031,
        elevation_m: 4.0,
    },
    StationData {
        id: "KCLE",
        name: "Cleveland, Ohio",
        lat: 41.4116,
        lon: -81.9590,
        elevation_m: 233.0,
    },
    StationData {
        id: "KCLX",
        name: "Charleston, South Carolina",
        lat: 32.6553,
        lon: -80.7484,
        elevation_m: 10.0,
    },
    StationData {
        id: "KCYS",
        name: "Cheyenne, Wyoming",
        lat: 41.1519,
        lon: -104.8061,
        elevation_m: 1866.0,
    },
    StationData {
        id: "KDAX",
        name: "Sacramento, California",
        lat: 38.2419,
        lon: -121.5900,
        elevation_m: 14.0,
    },
    StationData {
        id: "KDDC",
        name: "Dodge City, Kansas",
        lat: 37.7608,
        lon: -99.9683,
        elevation_m: 788.0,
    },
    StationData {
        id: "KDFX",
        name: "Laughlin Air Force Base, Texas",
        lat: 29.2736,
        lon: -100.7803,
        elevation_m: 331.0,
    },
    StationData {
        id: "KDIX",
        name: "Philadelphia, New Jersey",
        lat: 39.4375,
        lon: -74.4125,
        elevation_m: 45.0,
    },
    StationData {
        id: "KDLH",
        name: "Duluth, Minnesota",
        lat: 46.8369,
        lon: -92.2147,
        elevation_m: 435.0,
    },
    StationData {
        id: "KDMX",
        name: "Des Moines, Iowa",
        lat: 41.7206,
        lon: -93.7236,
        elevation_m: 295.0,
    },
    StationData {
        id: "KDOX",
        name: "Dover Air Force Base, Delaware",
        lat: 39.1283,
        lon: -75.4289,
        elevation_m: 15.0,
    },
    StationData {
        id: "KDTX",
        name: "Detroit, Michigan",
        lat: 42.6997,
        lon: -83.2875,
        elevation_m: 308.0,
    },
    StationData {
        id: "KDVN",
        name: "Davenport, Iowa",
        lat: 41.6117,
        lon: -90.5814,
        elevation_m: 230.0,
    },
    StationData {
        id: "KDYX",
        name: "Dyess Air Force Base, Texas",
        lat: 32.4119,
        lon: -99.8547,
        elevation_m: 546.0,
    },
    StationData {
        id: "KEAX",
        name: "Kansas City, Missouri",
        lat: 38.9856,
        lon: -94.5242,
        elevation_m: 283.0,
    },
    StationData {
        id: "KEMX",
        name: "Tucson, Arizona",
        lat: 31.8936,
        lon: -110.6308,
        elevation_m: 1551.0,
    },
    StationData {
        id: "KEOX",
        name: "Fort Benning, Georgia",
        lat: 32.5653,
        lon: -84.8369,
        elevation_m: 82.0,
    },
    StationData {
        id: "KEPZ",
        name: "El Paso, Texas",
        lat: 31.8728,
        lon: -106.6975,
        elevation_m: 1251.0,
    },
    StationData {
        id: "KESX",
        name: "Las Vegas, Nevada",
        lat: 35.7012,
        lon: -114.8914,
        elevation_m: 932.0,
    },
    StationData {
        id: "KEVX",
        name: "Fort Evans, Colorado",
        lat: 40.0533,
        lon: -104.6728,
        elevation_m: 1685.0,
    },
    StationData {
        id: "KEWX",
        name: "Austin/San Antonio, Texas",
        lat: 29.7106,
        lon: -98.0278,
        elevation_m: 188.0,
    },
    StationData {
        id: "KEYX",
        name: "Rancho Cucamonga, California",
        lat: 34.1753,
        lon: -117.6219,
        elevation_m: 433.0,
    },
    StationData {
        id: "KFCX",
        name: "Blaine, Washington",
        lat: 48.9964,
        lon: -122.7464,
        elevation_m: 111.0,
    },
    StationData {
        id: "KFDR",
        name: "Oklahoma City, Oklahoma",
        lat: 35.4161,
        lon: -98.1311,
        elevation_m: 379.0,
    },
    StationData {
        id: "KFDX",
        name: "Cannon Air Force Base, New Mexico",
        lat: 34.3828,
        lon: -103.3197,
        elevation_m: 1292.0,
    },
    StationData {
        id: "KFFX",
        name: "Pittsburgh, Pennsylvania",
        lat: 40.5316,
        lon: -79.9506,
        elevation_m: 395.0,
    },
    StationData {
        id: "KFSD",
        name: "Sioux Falls, South Dakota",
        lat: 43.5886,
        lon: -96.7692,
        elevation_m: 453.0,
    },
    StationData {
        id: "KFSX",
        name: "Flagstaff, Arizona",
        lat: 35.2331,
        lon: -111.3703,
        elevation_m: 2176.0,
    },
    StationData {
        id: "KFTG",
        name: "Denver, Colorado",
        lat: 39.7866,
        lon: -104.5456,
        elevation_m: 1675.0,
    },
    StationData {
        id: "KFWS",
        name: "Fort Worth, Texas",
        lat: 32.5733,
        lon: -97.3025,
        elevation_m: 173.0,
    },
    StationData {
        id: "KGRK",
        name: "Fort Hood, Texas",
        lat: 30.7219,
        lon: -97.3828,
        elevation_m: 308.0,
    },
    StationData {
        id: "KGRR",
        name: "Grand Rapids, Michigan",
        lat: 42.8922,
        lon: -85.5447,
        elevation_m: 237.0,
    },
    StationData {
        id: "KGJX",
        name: "Grand Junction, Colorado",
        lat: 39.0633,
        lon: -108.8847,
        elevation_m: 1459.0,
    },
    StationData {
        id: "KGLD",
        name: "Goodland, Kansas",
        lat: 39.3708,
        lon: -101.7003,
        elevation_m: 1116.0,
    },
    StationData {
        id: "KGRB",
        name: "Green Bay, Wisconsin",
        lat: 44.4808,
        lon: -87.9214,
        elevation_m: 209.0,
    },
    StationData {
        id: "KGRI",
        name: "Grand Island, Nebraska",
        lat: 40.9797,
        lon: -98.4178,
        elevation_m: 561.0,
    },
    StationData {
        id: "KGRK",
        name: "Fort Hood, Texas",
        lat: 30.7219,
        lon: -97.3828,
        elevation_m: 308.0,
    },
    StationData {
        id: "KGUF",
        name: "Biloxi, Mississippi",
        lat: 30.4133,
        lon: -88.9233,
        elevation_m: 8.0,
    },
    StationData {
        id: "KHGX",
        name: "Houston, Texas",
        lat: 29.4719,
        lon: -95.0808,
        elevation_m: 21.0,
    },
    StationData {
        id: "KHNX",
        name: "Hanford, California",
        lat: 36.3122,
        lon: -119.6303,
        elevation_m: 74.0,
    },
    StationData {
        id: "KHPX",
        name: "Fort Campbell, Kentucky",
        lat: 36.6686,
        lon: -87.2897,
        elevation_m: 175.0,
    },
    StationData {
        id: "KHWA",
        name: "Maui, Hawaii",
        lat: 20.9056,
        lon: -156.4333,
        elevation_m: 107.0,
    },
    StationData {
        id: "KICT",
        name: "Wichita, Kansas",
        lat: 37.6544,
        lon: -97.4406,
        elevation_m: 402.0,
    },
    StationData {
        id: "KICX",
        name: "Cedar City, Utah",
        lat: 37.5903,
        lon: -113.0992,
        elevation_m: 1703.0,
    },
    StationData {
        id: "KIDA",
        name: "Idaho Falls, Idaho",
        lat: 43.5122,
        lon: -112.0333,
        elevation_m: 1440.0,
    },
    StationData {
        id: "KIGX",
        name: "Raleigh/Durham, North Carolina",
        lat: 35.6653,
        lon: -78.9903,
        elevation_m: 138.0,
    },
    StationData {
        id: "KILN",
        name: "Cincinnati, Ohio",
        lat: 39.4289,
        lon: -84.0847,
        elevation_m: 314.0,
    },
    StationData {
        id: "KILX",
        name: "Lincoln, Illinois",
        lat: 40.1522,
        lon: -89.3367,
        elevation_m: 181.0,
    },
    StationData {
        id: "KIND",
        name: "Indianapolis, Indiana",
        lat: 39.7072,
        lon: -86.2808,
        elevation_m: 245.0,
    },
    StationData {
        id: "KINV",
        name: "Boise, Idaho",
        lat: 43.5647,
        lon: -116.2142,
        elevation_m: 860.0,
    },
    StationData {
        id: "KIWA",
        name: "Phoenix, Arizona",
        lat: 33.2889,
        lon: -111.6706,
        elevation_m: 412.0,
    },
    StationData {
        id: "KIWX",
        name: "Fort Wayne, Indiana",
        lat: 40.9753,
        lon: -85.1814,
        elevation_m: 251.0,
    },
    StationData {
        id: "KJAX",
        name: "Jacksonville, Florida",
        lat: 30.4839,
        lon: -81.7019,
        elevation_m: 11.0,
    },
    StationData {
        id: "KJGX",
        name: "Robins Air Force Base, Georgia",
        lat: 32.6403,
        lon: -83.3511,
        elevation_m: 89.0,
    },
    StationData {
        id: "KJKL",
        name: "Jackson, Kentucky",
        lat: 37.5936,
        lon: -83.3175,
        elevation_m: 417.0,
    },
    StationData {
        id: "KLBB",
        name: "Lubbock, Texas",
        lat: 33.6547,
        lon: -101.8147,
        elevation_m: 982.0,
    },
    StationData {
        id: "KLCH",
        name: "Lake Charles, Louisiana",
        lat: 30.2053,
        lon: -93.2186,
        elevation_m: 4.0,
    },
    StationData {
        id: "KLTX",
        name: "Wilmington, North Carolina",
        lat: 34.3636,
        lon: -77.9556,
        elevation_m: 27.0,
    },
    StationData {
        id: "KLVX",
        name: "Louisville, Kentucky",
        lat: 38.0342,
        lon: -85.6844,
        elevation_m: 213.0,
    },
    StationData {
        id: "KLWX",
        name: "Sterling, Virginia",
        lat: 38.9753,
        lon: -77.4778,
        elevation_m: 85.0,
    },
    StationData {
        id: "KLZT",
        name: "Fort Leonard Wood, Missouri",
        lat: 37.9719,
        lon: -92.1281,
        elevation_m: 341.0,
    },
    StationData {
        id: "KMAF",
        name: "Midland-Odessa, Texas",
        lat: 31.9408,
        lon: -102.1894,
        elevation_m: 874.0,
    },
    StationData {
        id: "KMBX",
        name: "Minot, North Dakota",
        lat: 48.3931,
        lon: -101.3347,
        elevation_m: 471.0,
    },
    StationData {
        id: "KMEG",
        name: "Memphis, Tennessee",
        lat: 35.0458,
        lon: -89.9819,
        elevation_m: 85.0,
    },
    StationData {
        id: "KMHX",
        name: "Morehead City, North Carolina",
        lat: 34.7753,
        lon: -76.8769,
        elevation_m: 10.0,
    },
    StationData {
        id: "KMIA",
        name: "Miami, Florida",
        lat: 25.6108,
        lon: -80.6853,
        elevation_m: 6.0,
    },
    StationData {
        id: "KMIC",
        name: "Minneapolis, Minnesota",
        lat: 44.9558,
        lon: -93.3286,
        elevation_m: 290.0,
    },
    StationData {
        id: "KMKX",
        name: "Milwaukee, Wisconsin",
        lat: 42.9683,
        lon: -88.5506,
        elevation_m: 285.0,
    },
    StationData {
        id: "KMLB",
        name: "Melbourne, Florida",
        lat: 28.1128,
        lon: -80.6814,
        elevation_m: 11.0,
    },
    StationData {
        id: "KMOB",
        name: "Mobile, Alabama",
        lat: 30.6869,
        lon: -88.0606,
        elevation_m: 65.0,
    },
    StationData {
        id: "KMPX",
        name: "Minneapolis, Minnesota",
        lat: 44.6139,
        lon: -93.3278,
        elevation_m: 288.0,
    },
    StationData {
        id: "KMQO",
        name: "Mount Pleasant, Texas",
        lat: 33.1042,
        lon: -94.9692,
        elevation_m: 109.0,
    },
    StationData {
        id: "KMRX",
        name: "Knoxville, Tennessee",
        lat: 36.0178,
        lon: -83.4025,
        elevation_m: 415.0,
    },
    StationData {
        id: "KMSX",
        name: "Missoula, Montana",
        lat: 46.9186,
        lon: -113.9864,
        elevation_m: 1185.0,
    },
    StationData {
        id: "KMTX",
        name: "Salt Lake City, Utah",
        lat: 41.2622,
        lon: -112.4508,
        elevation_m: 1305.0,
    },
    StationData {
        id: "KMUX",
        name: "San Francisco, California",
        lat: 37.1686,
        lon: -121.8403,
        elevation_m: 654.0,
    },
    StationData {
        id: "KMVX",
        name: "Grand Forks, North Dakota",
        lat: 47.5378,
        lon: -97.3281,
        elevation_m: 301.0,
    },
    StationData {
        id: "KMXX",
        name: "Maxwell Air Force Base, Alabama",
        lat: 32.3783,
        lon: -86.3528,
        elevation_m: 53.0,
    },
    StationData {
        id: "KNYX",
        name: "Fort Drum, New York",
        lat: 44.0567,
        lon: -75.7097,
        elevation_m: 207.0,
    },
    StationData {
        id: "KOAX",
        name: "Omaha, Nebraska",
        lat: 41.3203,
        lon: -96.3669,
        elevation_m: 350.0,
    },
    StationData {
        id: "KOHX",
        name: "Nashville, Tennessee",
        lat: 36.2478,
        lon: -86.5681,
        elevation_m: 180.0,
    },
    StationData {
        id: "KOKC",
        name: "Oklahoma City, Oklahoma",
        lat: 35.4094,
        lon: -97.6014,
        elevation_m: 370.0,
    },
    StationData {
        id: "KOTX",
        name: "Spokane, Washington",
        lat: 47.6586,
        lon: -117.4386,
        elevation_m: 571.0,
    },
    StationData {
        id: "KPAH",
        name: "Paducah, Kentucky",
        lat: 37.0589,
        lon: -88.7728,
        elevation_m: 125.0,
    },
    StationData {
        id: "KPBZ",
        name: "Pittsburgh, Pennsylvania",
        lat: 40.5316,
        lon: -79.9506,
        elevation_m: 395.0,
    },
    StationData {
        id: "KPDT",
        name: "Pendleton, Oregon",
        lat: 45.6914,
        lon: -118.8478,
        elevation_m: 458.0,
    },
    StationData {
        id: "KPOE",
        name: "Fort Polk, Louisiana",
        lat: 31.0472,
        lon: -93.1903,
        elevation_m: 84.0,
    },
    StationData {
        id: "KPUX",
        name: "Pueblo, Colorado",
        lat: 38.2847,
        lon: -104.3819,
        elevation_m: 1420.0,
    },
    StationData {
        id: "KRAX",
        name: "Raleigh, North Carolina",
        lat: 35.6653,
        lon: -78.9903,
        elevation_m: 138.0,
    },
    StationData {
        id: "KRDU",
        name: "Raleigh/Durham, North Carolina",
        lat: 35.6653,
        lon: -78.9903,
        elevation_m: 138.0,
    },
    StationData {
        id: "KRGX",
        name: "Reno, Nevada",
        lat: 39.5686,
        lon: -119.7708,
        elevation_m: 1518.0,
    },
    StationData {
        id: "KRIW",
        name: "Riverton, Wyoming",
        lat: 43.0672,
        lon: -108.4767,
        elevation_m: 1693.0,
    },
    StationData {
        id: "KRLX",
        name: "Charleston, West Virginia",
        lat: 38.3169,
        lon: -81.7228,
        elevation_m: 308.0,
    },
    StationData {
        id: "KRTX",
        name: "Portland, Oregon",
        lat: 45.7128,
        lon: -122.9658,
        elevation_m: 59.0,
    },
    StationData {
        id: "KSFX",
        name: "Pocatello, Idaho",
        lat: 42.8897,
        lon: -112.4261,
        elevation_m: 1363.0,
    },
    StationData {
        id: "KSGF",
        name: "Springfield, Missouri",
        lat: 37.2353,
        lon: -93.4006,
        elevation_m: 390.0,
    },
    StationData {
        id: "KSHV",
        name: "Shreveport, Louisiana",
        lat: 32.4508,
        lon: -93.7614,
        elevation_m: 78.0,
    },
    StationData {
        id: "KSIT",
        name: "Sitka, Alaska",
        lat: 57.0531,
        lon: -135.3617,
        elevation_m: 21.0,
    },
    StationData {
        id: "KSJX",
        name: "Sault Ste. Marie, Michigan",
        lat: 46.4719,
        lon: -84.3589,
        elevation_m: 226.0,
    },
    StationData {
        id: "KSKL",
        name: "Shelby, Montana",
        lat: 48.5386,
        lon: -111.8722,
        elevation_m: 1058.0,
    },
    StationData {
        id: "KSMX",
        name: "Santa Maria, California",
        lat: 34.8992,
        lon: -120.4586,
        elevation_m: 72.0,
    },
    StationData {
        id: "KSRX",
        name: "Fort Smith, Arkansas",
        lat: 35.3433,
        lon: -94.3983,
        elevation_m: 140.0,
    },
    StationData {
        id: "KSSX",
        name: "Salt Lake City, Utah",
        lat: 40.7683,
        lon: -112.0322,
        elevation_m: 1466.0,
    },
    StationData {
        id: "KTLH",
        name: "Tallahassee, Florida",
        lat: 30.3986,
        lon: -84.3289,
        elevation_m: 21.0,
    },
    StationData {
        id: "KTLX",
        name: "Oklahoma City, Oklahoma",
        lat: 35.4161,
        lon: -97.6311,
        elevation_m: 379.0,
    },
    StationData {
        id: "KTWX",
        name: "Topeka, Kansas",
        lat: 38.9719,
        lon: -95.7178,
        elevation_m: 333.0,
    },
    StationData {
        id: "KTYX",
        name: "Fort Drum, New York",
        lat: 44.0567,
        lon: -75.7097,
        elevation_m: 207.0,
    },
    StationData {
        id: "KUDX",
        name: "Rapid City, South Dakota",
        lat: 44.1292,
        lon: -103.2078,
        elevation_m: 920.0,
    },
    StationData {
        id: "KUEX",
        name: "Hastings, Nebraska",
        lat: 40.7314,
        lon: -98.4203,
        elevation_m: 596.0,
    },
    StationData {
        id: "KUIL",
        name: "Quillayute, Washington",
        lat: 47.9497,
        lon: -124.5564,
        elevation_m: 56.0,
    },
    StationData {
        id: "KUNR",
        name: "Rapid City, South Dakota",
        lat: 44.1292,
        lon: -103.2078,
        elevation_m: 920.0,
    },
    StationData {
        id: "KVBX",
        name: "Vandenberg Air Force Base, California",
        lat: 34.7292,
        lon: -120.4811,
        elevation_m: 117.0,
    },
    StationData {
        id: "KVNX",
        name: "Vance Air Force Base, Oklahoma",
        lat: 36.7431,
        lon: -98.0756,
        elevation_m: 375.0,
    },
    StationData {
        id: "KVTX",
        name: "Ventura, California",
        lat: 34.2097,
        lon: -119.1858,
        elevation_m: 152.0,
    },
    StationData {
        id: "KVWX",
        name: "Evansville, Indiana",
        lat: 38.0806,
        lon: -87.6778,
        elevation_m: 169.0,
    },
    StationData {
        id: "KYUX",
        name: "Yuma, Arizona",
        lat: 32.6569,
        lon: -114.4706,
        elevation_m: 63.0,
    },
    // Alaska Stations
    StationData {
        id: "PABC",
        name: "Bethel, Alaska",
        lat: 60.7892,
        lon: -161.8764,
        elevation_m: 42.0,
    },
    StationData {
        id: "PAEC",
        name: "Elmendorf Air Force Base, Alaska",
        lat: 61.2669,
        lon: -149.7947,
        elevation_m: 64.0,
    },
    StationData {
        id: "PAFG",
        name: "Fairbanks, Alaska",
        lat: 64.8353,
        lon: -147.6514,
        elevation_m: 137.0,
    },
    StationData {
        id: "PAGL",
        name: "Galena, Alaska",
        lat: 64.6942,
        lon: -156.8808,
        elevation_m: 36.0,
    },
    StationData {
        id: "PAHG",
        name: "Anchorage, Alaska",
        lat: 61.1758,
        lon: -149.8236,
        elevation_m: 48.0,
    },
    StationData {
        id: "PAIH",
        name: "St. Paul Island, Alaska",
        lat: 57.1544,
        lon: -170.2206,
        elevation_m: 17.0,
    },
    StationData {
        id: "PAKC",
        name: "King Salmon, Alaska",
        lat: 58.6917,
        lon: -156.6292,
        elevation_m: 17.0,
    },
    StationData {
        id: "PALU",
        name: "Barrow, Alaska",
        lat: 71.3231,
        lon: -156.6114,
        elevation_m: 8.0,
    },
    StationData {
        id: "PAMC",
        name: "McGrath, Alaska",
        lat: 62.9514,
        lon: -155.6239,
        elevation_m: 103.0,
    },
    StationData {
        id: "PANA",
        name: "Napaskiak, Alaska",
        lat: 60.7081,
        lon: -161.7783,
        elevation_m: 16.0,
    },
    StationData {
        id: "PAOM",
        name: "Nome, Alaska",
        lat: 64.5086,
        lon: -165.4153,
        elevation_m: 12.0,
    },
    StationData {
        id: "PAOR",
        name: "Northway, Alaska",
        lat: 62.9619,
        lon: -141.9292,
        elevation_m: 522.0,
    },
    StationData {
        id: "PAQT",
        name: "Nuiqsut, Alaska",
        lat: 70.2178,
        lon: -151.0147,
        elevation_m: 10.0,
    },
    StationData {
        id: "PARC",
        name: "Arctic Village, Alaska",
        lat: 68.1147,
        lon: -145.5283,
        elevation_m: 209.0,
    },
    StationData {
        id: "PASD",
        name: "Sand Point, Alaska",
        lat: 55.3311,
        lon: -160.5236,
        elevation_m: 10.0,
    },
    StationData {
        id: "PASN",
        name: "St. Paul Island, Alaska",
        lat: 57.1544,
        lon: -170.2206,
        elevation_m: 17.0,
    },
    StationData {
        id: "PASX",
        name: "Soldotna, Alaska",
        lat: 60.4758,
        lon: -151.2408,
        elevation_m: 33.0,
    },
    StationData {
        id: "PATA",
        name: "Tanana, Alaska",
        lat: 65.1792,
        lon: -152.0667,
        elevation_m: 67.0,
    },
    StationData {
        id: "PATC",
        name: "St. George, Alaska",
        lat: 56.6014,
        lon: -169.5483,
        elevation_m: 8.0,
    },
    StationData {
        id: "PAUM",
        name: "Uummannaq, Greenland",
        lat: 70.6758,
        lon: -52.1253,
        elevation_m: 8.0,
    },
    // Hawaii Stations
    StationData {
        id: "PHFO",
        name: "Honolulu, Hawaii",
        lat: 21.4492,
        lon: -158.2133,
        elevation_m: 17.0,
    },
    StationData {
        id: "PHKI",
        name: "Kauai, Hawaii",
        lat: 22.0992,
        lon: -159.6667,
        elevation_m: 32.0,
    },
    StationData {
        id: "PHKM",
        name: "Kamuela, Hawaii",
        lat: 20.0044,
        lon: -155.6667,
        elevation_m: 1077.0,
    },
    StationData {
        id: "PHLU",
        name: "Lahaina, Hawaii",
        lat: 20.8767,
        lon: -156.6833,
        elevation_m: 15.0,
    },
    // Puerto Rico Station
    StationData {
        id: "TJUA",
        name: "San Juan, Puerto Rico",
        lat: 18.4655,
        lon: -66.2158,
        elevation_m: 215.0,
    },
    // Guam Station
    StationData {
        id: "PGUA",
        name: "Guam",
        lat: 13.4536,
        lon: 144.8183,
        elevation_m: 82.0,
    },
    // Virgin Islands
    StationData {
        id: "TISX",
        name: "St. Croix, US Virgin Islands",
        lat: 17.7344,
        lon: -64.8044,
        elevation_m: 30.0,
    },
];

/// Compact station data structure for embedded metadata.
///
/// This struct is used internally to store station data in a const context
/// and is converted to the public `Station` type at runtime.
#[derive(Debug, Clone, Copy)]
pub(crate) struct StationData {
    /// 4-letter ICAO identifier
    pub id: &'static str,
    /// Human-readable station name
    pub name: &'static str,
    /// Latitude in decimal degrees
    pub lat: f64,
    /// Longitude in decimal degrees
    pub lon: f64,
    /// Station elevation in meters
    pub elevation_m: f32,
}
